{% set name = "hillmaker" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hillmaker-{{ version }}.tar.gz
  sha256: 762b02016b358f537f698a2ee1348a8fcf0df505d70c9c3fa05f825f6c7e19b4

build:
  entry_points:
    - hillmaker=hillmaker.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.0.0
    - numpy >=1.22
    - tomli >=2.0.1
    - matplotlib-base >=3.7.1
    - pydantic >=2.1.1
    - seaborn >=0.12.2
    - jinja2
    - ipykernel

test:
  imports:
    - hillmaker
  commands:
    - pip check
    - hillmaker --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/misken/hillmaker/
  summary: Occupancy analysis tool for systems having time of day and day of week effects
  dev_url: http://github.com/misken/hillmaker
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - misken
